### ISSUE TITLE
the training

### ISSUE THREAD

**Issue by wolfworld6** [yuqj1990/caffe_train#18]
i have training with your code，the loss as follows，
![image](https://user-images.githubusercontent.com/18051979/100813330-14875500-347a-11eb-8df3-7c7db28aa056.png)
but the inference is not right，how i to solve it？

**Comment by yuqj1991** [comment]
wide-face？did you use nms？modify the nms threshold

**Comment by yuqj1991** [comment]
> i have training with your code，the loss as follows，
> ![image](https://user-images.githubusercontent.com/18051979/100813330-14875500-347a-11eb-8df3-7c7db28aa056.png)
> but the inference is not right，how i to solve it？

wide-face？did you use nms？modify the nms threshold

**Comment by wolfworld6** [comment]
> > i have training with your code，the loss as follows，
> > ![image](https://user-images.githubusercontent.com/18051979/100813330-14875500-347a-11eb-8df3-7c7db28aa056.png)
> > but the inference is not right，how i to solve it？
> 
> wide-face？did you use nms？modify the nms threshold

yeah.wider_face. i dont know why the pre box is not right,nms=0.3,as follows:
![Uploading image.png…]()

**Comment by yuqj1991** [comment]
> i have training with your code，the loss as follows，
> 
> but the inference is not right，how i to solve it？
> 
> wide-face？did you use nms？modify the nms threshold
> 
> yeah.wider_face. i dont know why the pre box is not right,nms=0.3,as follows:

cannot see the log

**Comment by wolfworld6** [comment]
> > i have training with your code，the loss as follows，
> > but the inference is not right，how i to solve it？
> > wide-face？did you use nms？modify the nms threshold
> > yeah.wider_face. i dont know why the pre box is not right,nms=0.3,as follows:
> 
> cannot see the log

the inference as follows：
![image](https://user-images.githubusercontent.com/18051979/102572670-ab653a00-4127-11eb-8646-199d198df8c0.png)

**Comment by yuqj1991** [comment]
alright! it looks like very strange, maybe your confidence threshold set too high?  i dont know what's your trainning process! what's your map result of the validate in the training porcess? i have long time not to do this related work. And i remember i used to send you my model . i dont know whether it is  you! i have ever send my model to some one!

**Comment by yuqj1991** [comment]
> > > i have training with your code，the loss as follows，
> > > but the inference is not right，how i to solve it？
> > > wide-face？did you use nms？modify the nms threshold
> > > yeah.wider_face. i dont know why the pre box is not right,nms=0.3,as follows:
> > 
> > 
> > cannot see the log
> 
> the inference as follows：
> ![image](https://user-images.githubusercontent.com/18051979/102572670-ab653a00-4127-11eb-8646-199d198df8c0.png)

alright! it looks like very strange, maybe your confidence threshold set too high? i don't know what's your training process! what's your map result of the validate in the training process? i have long time not to do this related work. And i remember i used to send you my model . i don't know whether it is you! i have ever send my model to some one!
