### ISSUE TITLE
face_list_lfw.txt和face_list_lfw_gt.txt不能由face_labels_gen.py生成，它俩的区别以及求文件

### ISSUE THREAD

**Issue by WW2401** [yuqj1990/caffe_train#2]
你好！我看了你的example/face/recognition/caffe里的实例，非常有用，方便提供一下你的face_list_lfw.txt以及face_list_lfw_gt.txt吗？ 非常感谢@yuqj1990

**Comment by yuqj1990** [comment]
你好，这个用脚本face_labels_gen.py可以生成

**Comment by WW2401** [comment]
> 你好，这个用脚本face_labels_gen.py可以生成

face_list_lfw.txt 和face_list_lfw_gt.txt区别是啥？face_labels_gen.py不是只生成标签文件吗?而face_similarity.py是生成两个图片的相似度，是不是应该有关于两个图片是否是同一人的标签文件？

**Comment by WW2401** [comment]
face_labels_gen.py不是只生成标签文件吗?而face_similarity.py是生成两个图片的相似度，是不是应该有关于两个图片是否是同一人的标签文件？face_list_lfw_gt.txt是pair.txt吗？face_list_lfw.txt 和face_list_lfw_gt.txt区别是啥？       @yuqj1990
