### ISSUE TITLE
face_list_lfw.txt和face_list_lfw_gt.txt不能由face_labels_gen.py生成，它俩的区别以及求文件

### ISSUE THREAD

**Issue by WW2401** [yuqj1990/caffe_train#3]
face_similarity.py是生成两个图片的相似度，是不是应该有关于两个图片是否是同一人的标签文件？face_list_lfw_gt.txt是pair.txt吗？face_list_lfw.txt 和face_list_lfw_gt.txt区别是啥？
从face_similary.py里的path1, path2= line.strip('\n').split(' ')可看出一行有两张图片的路径，而face_labels_gen.py生成的一行只有一张图片的路径。
最近急需画ROC曲线，迫切求解答啊 非常感谢@yuqj1990

**Comment by yuqj1990** [comment]
face_labels_gen.py是生成训练时label的脚本，face_similary.py 是求取相似度的，你看的没错？至于如何生成pair.txt 这个应该不难吧！写个脚本很容易吧

**Comment by WW2401** [comment]
> face_labels_gen.py是生成训练时label的脚本，face_similary.py 是求取相似度的，你看的没错？至于如何生成pair.txt 这个应该不难吧！写个脚本很容易吧
求问face_list_lfw_gt.txt 和face_list_lfw.txt区别是什么？face_list_lfw_gt.txt 怎么生成？

**Comment by WW2401** [comment]
> face_labels_gen.py是生成训练时label的脚本，face_similary.py 是求取相似度的，你看的没错？至于如何生成pair.txt 这个应该不难吧！写个脚本很容易吧

求问face_list_lfw_gt.txt 和face_list_lfw.txt区别是什么？face_list_lfw_gt.txt 怎么生成？

**Comment by yuqj1990** [comment]
写个脚本生成他呗，这里面没有这个脚本生成他，你自己生成他呗

**Comment by WW2401** [comment]
> 写个脚本生成他呗，这里面没有这个脚本生成他，你自己生成他呗

主要是我不知道face_list_lfw_gt.txt是什么？和face_list_lfw.txt的区别在哪？

**Comment by WW2401** [comment]
> 写个脚本生成他呗，这里面没有这个脚本生成他，你自己生成他呗

主要是我不知道face_list_lfw_gt.txt是什么？能告诉一下face_list_lfw_gt.txt是什么以及和face_list_lfw.txt的区别在哪吗？如果知道是什么就好写些了。
