### ISSUE TITLE
face_list_lfw_gt.txt是什么？

### ISSUE THREAD

**Issue by youthM** [yuqj1990/caffe_train#4]
你好，想问下caffe_train/examples/face/recognition/caffe/scripts/中roc_curve.py时的face_list_lfw_gt.txt是什么？是不是和face_list_lfw.txt不一样？Thanks a lot. @yuqj1990

**Comment by yuqj1990** [comment]
我已经更新，有需要自取

**Comment by youthM** [comment]
谢谢
