### ISSUE TITLE
关于 Reid 的问题

### ISSUE THREAD

**Issue by WangYX-TKZ** [yuqj1990/caffe_train#8]
你好，我是第一次接触Reid，想问下：
1.如果使用项目中 caffe的Reid，数据集如何准备。
2.我看到train prototxt中用了多级的模式，想请教下看哪篇论文容易理解原理。
如果能够得到回答，万分感谢

**Comment by yuqj1990** [comment]
你好，感谢提问！本项目中的数据集准备，由于我使用了tripletloss，因此，我是在线选择样本，可以参考，facenet的tripleloss是如何准备的，其实比较简单，我这里打乱了顺序。
至于你说的多级模式，我不知道你想表达什么，你是想说明局部和全局特征吗？这方面论文很多
