### ISSUE TITLE
memory

### ISSUE THREAD

**Issue by wolfworld6** [yuqj1990/caffe_train#9]
hello，thanks a lot for your release code，i wanna know  you do something about memory optimization？

**Comment by yuqj1990** [comment]
e...yes, now i am doing to merge convolution , bn & scale to one layer

**Comment by wolfworld6** [comment]
> e...yes, now i am doing to merge convolution , bn & scale to one layer
thanks


> e...yes, now i am doing to merge convolution , bn & scale to one layer

another question about protobuf，the version you are using？

**Comment by yuqj1990** [comment]
2.6.1
